In [7]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [8]:
# Generate some synthetic data
x = np.random.rand(1000, 10) * 10
y = 2.5 * x + np.random.randn(1000, 1) * 2
x, y

(array([[2.56310186, 1.50923421, 1.33005981, ..., 9.70260366, 2.2404425 ,
         7.55549658],
        [6.02380029, 3.88488878, 7.40208719, ..., 9.46654716, 0.22332242,
         0.12171853],
        [3.50484356, 6.74082955, 1.20808638, ..., 3.00866954, 9.74478795,
         5.74060767],
        ...,
        [6.99782937, 4.84010959, 3.87296274, ..., 4.25060368, 7.89125212,
         2.83433678],
        [3.42762987, 8.36262111, 9.26694312, ..., 3.77996034, 0.6752636 ,
         4.25661433],
        [0.40545447, 6.48341294, 1.97682481, ..., 8.98177903, 4.27499607,
         4.34542686]]),
 array([[ 7.30933688,  4.67466777,  4.22673176, ..., 25.15809139,
          6.5026885 , 19.7903237 ],
        [12.31301497,  6.96573619, 15.75873221, ..., 20.91988214,
         -2.18817971, -2.44218942],
        [ 8.62935841, 16.71932339,  2.88746546, ...,  7.38892336,
         24.2292194 , 14.21876869],
        ...,
        [20.8531639 , 15.45886444, 13.04099733, ..., 13.98509966,
         23.08672077, 10

In [9]:
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [10]:
# Create and train the model
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [11]:
# Make predictions and evaluate the model
y_pred = model.predict(x_test)
y_pred

array([[24.11307401, 17.09954254,  3.63670527, ..., 16.68959346,
        11.76898409, 15.42726916],
       [ 6.56125937, 23.03208584, 25.06637166, ..., 21.35582715,
         3.63511168, 23.97014253],
       [ 6.82491339, 14.6315134 , 11.36868685, ..., 13.53922837,
        13.03014367, 11.34217779],
       ...,
       [ 8.19757651, 19.24170674, 13.45721098, ..., 23.91805264,
        16.69623594, 15.22892454],
       [19.06344129,  1.2497194 , 19.23611223, ...,  7.6458169 ,
         0.96697446,  8.96740013],
       [ 0.13893036,  2.8088484 ,  3.50516856, ..., 19.62319118,
        16.16022846, 21.83223799]])